/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StandingsRouteImport } from './routes/standings'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RosterRouteImport } from './routes/roster'
import { Route as PackRouteImport } from './routes/pack'
import { Route as MarketRouteImport } from './routes/market'
import { Route as LineupRouteImport } from './routes/lineup'
import { Route as GameRouteImport } from './routes/game'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayerPlayerIdRouteImport } from './routes/player.$playerId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StandingsRoute = StandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterRoute = RosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => rootRouteImport,
} as any)
const PackRoute = PackRouteImport.update({
  id: '/pack',
  path: '/pack',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const LineupRoute = LineupRouteImport.update({
  id: '/lineup',
  path: '/lineup',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerPlayerIdRoute = PlayerPlayerIdRouteImport.update({
  id: '/player/$playerId',
  path: '/player/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/game': typeof GameRoute
  '/lineup': typeof LineupRoute
  '/market': typeof MarketRoute
  '/pack': typeof PackRoute
  '/roster': typeof RosterRoute
  '/settings': typeof SettingsRoute
  '/standings': typeof StandingsRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/player/$playerId': typeof PlayerPlayerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/game': typeof GameRoute
  '/lineup': typeof LineupRoute
  '/market': typeof MarketRoute
  '/pack': typeof PackRoute
  '/roster': typeof RosterRoute
  '/settings': typeof SettingsRoute
  '/standings': typeof StandingsRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/player/$playerId': typeof PlayerPlayerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/game': typeof GameRoute
  '/lineup': typeof LineupRoute
  '/market': typeof MarketRoute
  '/pack': typeof PackRoute
  '/roster': typeof RosterRoute
  '/settings': typeof SettingsRoute
  '/standings': typeof StandingsRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/player/$playerId': typeof PlayerPlayerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/game'
    | '/lineup'
    | '/market'
    | '/pack'
    | '/roster'
    | '/settings'
    | '/standings'
    | '/terms'
    | '/wallet'
    | '/welcome'
    | '/player/$playerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/game'
    | '/lineup'
    | '/market'
    | '/pack'
    | '/roster'
    | '/settings'
    | '/standings'
    | '/terms'
    | '/wallet'
    | '/welcome'
    | '/player/$playerId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/game'
    | '/lineup'
    | '/market'
    | '/pack'
    | '/roster'
    | '/settings'
    | '/standings'
    | '/terms'
    | '/wallet'
    | '/welcome'
    | '/player/$playerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  GameRoute: typeof GameRoute
  LineupRoute: typeof LineupRoute
  MarketRoute: typeof MarketRoute
  PackRoute: typeof PackRoute
  RosterRoute: typeof RosterRoute
  SettingsRoute: typeof SettingsRoute
  StandingsRoute: typeof StandingsRoute
  TermsRoute: typeof TermsRoute
  WalletRoute: typeof WalletRoute
  WelcomeRoute: typeof WelcomeRoute
  PlayerPlayerIdRoute: typeof PlayerPlayerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standings': {
      id: '/standings'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof StandingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster': {
      id: '/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof RosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pack': {
      id: '/pack'
      path: '/pack'
      fullPath: '/pack'
      preLoaderRoute: typeof PackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lineup': {
      id: '/lineup'
      path: '/lineup'
      fullPath: '/lineup'
      preLoaderRoute: typeof LineupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$playerId': {
      id: '/player/$playerId'
      path: '/player/$playerId'
      fullPath: '/player/$playerId'
      preLoaderRoute: typeof PlayerPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  GameRoute: GameRoute,
  LineupRoute: LineupRoute,
  MarketRoute: MarketRoute,
  PackRoute: PackRoute,
  RosterRoute: RosterRoute,
  SettingsRoute: SettingsRoute,
  StandingsRoute: StandingsRoute,
  TermsRoute: TermsRoute,
  WalletRoute: WalletRoute,
  WelcomeRoute: WelcomeRoute,
  PlayerPlayerIdRoute: PlayerPlayerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
